server:
  port: 9000

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sportplay?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

# mybatis
mybatis:
  type-aliases-package: com.wuyiz.sportplay.entity
  mapper-locations: classpath*:mapper/*.xml

